### PR TITLE
more flexible version of the adblock-update.sh script

### PR DESCRIPTION
**Pull request by md2501**
This includes t-8ch fixes. It may be further improved in the future (-a, --all flag).

### CODE REVIEW

**Comment by Plaque-fcc** [comment]
Can merge and adapt more. Looks acceptable.

**Comment by Plaque-fcc** [comment]
@Doomicide, you can still push to Plaque-fcc/luakit-adblock, changes will be cross-merged appropriately.
For the first time, I did not place adblock-update.sh script into mason-larobina/luakit-plugins until we decide where should we put it there. Maybe @mason-larobina has got any suggestions.

**Comment by md2501** [comment]
Ok, I didn't know I could push directly to it in the first place. How about somewhere in /usr/share/luakit/lib/_plugins/adblock_ or in $XDG_DATA_HOME/luakit/adblock of the respective user.

**Comment by Plaque-fcc** [comment]
Please, take a look at [luakit-plugins](https://github.com/mason-larobina/luakit-plugins) first, okay? ;D

**Comment by md2501** [comment]
Haha, I thought install-directories. That were just some suggestions from the top of my head. Maybe I should think more before posting :))

**Comment by Plaque-fcc** [comment]
Do whatever ever keeps you imagine! ;“D

  Well, our primary goal is to achieve some experience; I'm rather new
both to Lua and Github, so I started to read Roberto's old good book
about his Lua. What I have to say is that Lua seems to be as close to
what I ever needed among PLs as nothing ever seen with my eyes.

  I `ln -s ’-ed luakit-plugins repo to my ~/.config/luakit/, and
now it's ~/.config/luakit/plugins/ symlink. Maybe, we should think of
it a bit more, but at the moment it is just what it is, and I'd like
everyone to enhance its approach without cardinally breaking of the
main idea of having less hardcoded configs and more those separated
from the code. Like our «subscriptions» file can be an example of.

**Pull request merged**
